### User creation Admin

POST http://localhost:3001/ezelectronics/users HTTP/1.1
Content-Type: application/json

{
    "username": "mariorossi",
    "name": "Mario",
    "surname": "Rossi",
    "password": "ezelectronics",
    "role": "Admin"
}

### User creation Customer

POST http://localhost:3001/ezelectronics/users HTTP/1.1
Content-Type: application/json

{
    "username": "andreapani",
    "name": "Andrea",
    "surname": "Pani",
    "password": "ezelectronics",
    "role": "Customer"
}

########## AUTHENTICATION

### Login of Admin

POST http://localhost:3001/ezelectronics/sessions HTTP/1.1
Content-type: application/json

{
    "username": "mariorossi",
    "password": "ezelectronics"
}

### Login of Customer

POST http://localhost:3001/ezelectronics/sessions HTTP/1.1
Content-type: application/json

{
    "username": "andreapani",
    "password": "ezelectronics"
}

########## CART APIs

### GET ezelectronics/carts (Get the current unpaid cart for the customer)
GET http://localhost:3001/ezelectronics/carts HTTP/1.1

### POST ezelectronics/carts (Add a product to the cart)
POST http://localhost:3001/ezelectronics/carts HTTP/1.1
Content-type: application/json

{
    "model": "Dell XPS 15"
}

### PATCH ezelectronics/carts (Cart payment)
PATCH http://localhost:3001/ezelectronics/carts HTTP/1.1

### GET ezelectronics/carts/history (Get the cart history of the customer)
GET http://localhost:3001/ezelectronics/carts/history HTTP/1.1

### DELETE ezelectronics/carts/products/:model (Remove a product from the cart)
DELETE http://localhost:3001/ezelectronics/carts/products/Iphone%2013 HTTP/1.1

### DELETE ezelectronics/carts/current (Empties the current cart of the customer)
DELETE http://localhost:3001/ezelectronics/carts/current HTTP/1.1

### DELETE ezelectronics/carts (Removes all the carts in the database (Admin/Manager))
DELETE http://localhost:3001/ezelectronics/carts HTTP/1.1

### GET ezelectronics/carts/all (Get all the carts (Admin/Manager))
GET http://localhost:3001/ezelectronics/carts/all HTTP/1.1



########## REVIEW APIs

### POST ezelectronics/reviews/:model (Add a review for a product)
POST http://localhost:3001/ezelectronics/reviews/Iphone%2013 HTTP/1.1
Content-type: application/json

{
    "score": 5,
    "comment": "A very cool smartphone!"
}

### GET ezelectronics/reviews/:model (Get all reviews of a product)
GET http://localhost:3001/ezelectronics/reviews/Iphone%2013 HTTP/1.1

### DELETE ezelectronics/reviews/:model (Delete a customer review for a product)
DELETE http://localhost:3001/ezelectronics/reviews/Iphone%2013 HTTP/1.1

### DELETE ezelectronics/reviews/:model/all (Delete all reviews for a product)
DELETE http://localhost:3001/ezelectronics/reviews/Iphone%2013/all HTTP/1.1

### DELETE ezelectronics/reviews (Delete all reviews)
DELETE http://localhost:3001/ezelectronics/reviews HTTP/1.1




########## PRODUCTS APIs

### POST ezelectronics/products (Insert a set of products)
POST http://localhost:3001/ezelectronics/products HTTP/1.1
Content-type: application/json

{
    "model": "Samsung S24",
    "category": "Smartphone",
    "quantity": 3,
    "details": "The latest smartphone from Samsung",
    "sellingPrice": 929.0,
    "arrivalDate": "2024-01-01"
}

### GET ezelectronics/products (Get all products)
GET http://localhost:3001/ezelectronics/products?grouping=category&category=Laptop HTTP/1.1

### PATCH ezelectronics/products/:model(Increase quantity of product)
PATCH http://localhost:3001/ezelectronics/products/Iphone%2013 HTTP/1.1
Content-Type: application/json

{
    "quantity": 2,
    "changeDate": "2023-06-01"
}

### PATCH ezelectronics/products/sell (Sell Products)

PATCH http://localhost:3001/ezelectronics/products/Iphone%2013/sell HTTP/1.1
Content-Type: application/json


{
    "quantity": 2,
    "sellingDate": "2023-06-15"
}

### GET ezelectronics/products/available (Get Available Products)
GET http://localhost:3001/ezelectronics/products/available HTTP/1.1


### GET ezelectronics/products?grouping=category&category=Smartphone (Get All Products by Category)
GET http://localhost:3001/ezelectronics/products?grouping=category&category=Smartphone HTTP/1.1


### GET ezelectronics/products?grouping=model&model=iPhone14 (Get All Products by Model)
GET http://localhost:3001/ezelectronics/products?grouping=model&model=iPhone14 HTTP/1.1


### DELETE ezelectronics/products (Delete All Products)
DELETE http://localhost:3001/ezelectronics/products HTTP/1.1


### DELETE ezelectronics/products/:model(Delete Product by Model)
DELETE http://localhost:3001/ezelectronics/products/iPhone15 HTTP/1.1



########## USER APIs

### POST ezelectronics/users (creates a new user)
POST http://localhost:3001/ezelectronics/users
Content-Type: application/json

{
    "username": "testuser",
    "name": "Test",
    "surname": "User",
    "password": "ezlectronics",
    "role": "Manager"
}

### GET ezelectronics/users (returns the list of all users (Admin))
GET http://localhost:3001/ezelectronics/users HTTP/1.1

### GET ezelectronics/users/roles/:role (returns the list of users with a specific role (Admin))
GET http://localhost:3001/ezelectronics/users/roles/Customer HTTP/1.1


### Update User Info
PATCH http://localhost:3001/ezelectronics/users/mariorossi HTTP/1.1
Content-Type: application/json

{
    "name":"Mario",
    "surname":"Rossi",
    "address":"Corso Duca",
    "birthdate":"2012-12-12"
}







